services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: product-db
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
